version: '3.9'
services:
  node-app:
    build:
      dockerfile: Dockerfile
      context: ./backend
      args:
        NODE_ENV: development
    volumes:
      - ./backend/:/backend-app:ro #Read Only Bind Mount Volume
      - /backend-app/node_modules #Anonymous Volume to Prevent Bind Mount From Overwriting node_modules In Container
    environment:
      - NODE_ENV=development
      - MONGO_USER=myusername
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secretja
    command: npm run dev
  scraping-app:
    build:
      dockerfile: Dockerfile
      context: ./scraping
      args:
        NODE_ENV: development
    volumes:
      - ./scraping/:/scraping-app:ro #Read Only Bind Mount Volume
      - /scraping-app/node_modules #Anonymous Volume
    environment:
      - NODE_ENV=development
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myusername
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
  quasar:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      args:
        NODE_ENV: development
    volumes:
      - ./frontend/:/frontend-app #Read Only Bind Mount Volume
      - /frontend-app/node_modules #Anonymous Volume
  filter:
    build:
      dockerfile: Dockerfile
      context: ./filter
    ports:
      - '5000:5000'
    volumes:
      - ./filter/:/filter-app
    environment:
      FLASK_ENV: development
