version: '3.9'
services:
  nginx:
    ports:
      - '80:80'
  node-app:
    build:
      dockerfile: Dockerfile
      context: ./backend
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    command: npm run start
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  filter:
    build:
      dockerfile: Dockerfile
      context: ./filter
  twint:
    build:
      dockerfile: Dockerfile
      context: ./twint
