version: '3.9'
services:
  node-app:
    build:
      dockerfile: Dockerfile
      context: ./backend
      args:
        NODE_ENV: development
    volumes:
      - ./backend/:/backend:ro #Read Only Bind Mount Volume
      - /backend/node_modules #Anonymous Volume
    environment:
      - NODE_ENV=development
      - MONGO_USER=myusername
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secretja
    command: npm run dev
  scraping-app:
    build:
      dockerfile: Dockerfile
      context: ./scraping
      args:
        NODE_ENV: development
    volumes:
      - ./scraping/:/scraping:ro #Read Only Bind Mount Volume
      - /scraping/node_modules #Anonymous Volume
    environment:
      - NODE_ENV=development
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myusername
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
  vue-ui:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      args:
        NODE_ENV: development
    volumes:
      - ./frontend/:/frontend:ro #Read Only Bind Mount Volume
      - /frontend/node_modules #Anonymous Volume
