version: '3.9'
services:
  node-app:
    build: .
    ports:
      - '3000:8080'
    environment:
      - PORT=3000

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myusername
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db #Named Volume

volumes:
  mongo-db:
