version: '3.9'
services:
  nginx:
    ports:
      - '8000:80'
  node-app:
    build:
      dockerfile: Dockerfile
      context: ./backend
      args:
        NODE_ENV: development
    volumes:
      - ./backend/src:/backend-app/src:ro #Read Only Bind Mount Volume
      - /backend-app/node_modules #Anonymous Volume to Prevent Bind Mount From Overwriting node_modules In Container
    environment:
      - NODE_ENV=development
      - MONGO_USER=myusername
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secretja
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myusername
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
  quasar:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      args:
        NODE_ENV: development
    volumes:
      - ./frontend/:/frontend-app #Read Only Bind Mount Volume
      - /frontend-app/node_modules #Anonymous Volume
    command: npm run serve

  filter:
    build:
      dockerfile: Dockerfile
      context: ./filter
    ports:
      - '5000:5000'
    volumes:
      - ./filter/:/filter-app
    environment:
      FLASK_ENV: development
  twint:
    build:
      dockerfile: Dockerfile
      context: ./twint
    ports:
      - '6000:6000'
    volumes:
      - ./twint/:/twint-app
    environment:
      FLASK_ENV: development
