version: '3.9'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro #Read Only Bind Mount Volume
      - /app/node_modules #Anonymous Volume
    environment:
      - NODE_ENV=development
    command: npm run dev
