version: '3.9'
services:
  nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: nginx

  node-app:
    build: .
    image: ghcr.io/me-dev-house/rtma-node:latest
    environment:
      - PORT=3000
    depends_on:
      - mongo
      - redis
      - nginx

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myusername
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db #Named Volume
    container_name: mongo
    ports:
      - '27018:27017'

  redis:
    image: redis
    container_name: redis

  quasar:
    build: .
    image: ghcr.io/me-dev-house/rtma-quasar:latest
    ports:
      - '8080:8080'

  filter:
    build: .
    image: ghcr.io/me-dev-house/rtma-filter:latest
    ports:
      - '5000:5000'
    container_name: filter
    depends_on:
      - node-app

  twint:
    build: .
    image: ghcr.io/me-dev-house/rtma-twint:latest
    ports:
      - '6000:6000'
    container_name: twint
    depends_on:
      - node-app

volumes:
  mongo-db:
