version: '3.9'
services:
  nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: nginx

  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo
    container_name: node-app

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myusername
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db #Named Volume
    container_name: mongo

  redis:
    image: redis
    container_name: redis

  vue-ui:
    build: .
    ports:
      - '8080:8080'
    container_name: vue-ui

volumes:
  mongo-db:
