#Stage 1
FROM node:14.17.3 as builder
WORKDIR /backend-app
COPY package*.json .
COPY . .
RUN npm install
RUN npm run clean
RUN npm run build

#Stage 2
FROM node:14.17.3
WORKDIR /backend-app
COPY package*.json .
RUN npm install --only=production
COPY --from=builder /backend-app/dist ./dist

ENV PORT 3000
EXPOSE $PORT
CMD npm run start


