# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  npm_test_node-app:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM INSTALL
      working-directory: ${{env.working-directory}}
      run: npm ci
    - name: NPM RUN BUILD (If Present)
      working-directory: ${{env.working-directory}}
      run: npm run build --if-present
    - name: NPM TEST (If Present)
      working-directory: ${{env.working-directory}}
      run: npm test --if-present

  npm_test_vue-ui:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM INSTALL
      working-directory: ${{env.working-directory}}
      run: npm ci
    - name: NPM RUN BUILD (If Present)
      working-directory: ${{env.working-directory}}
      run: npm run build --if-present
    - name: NPM TEST (If Present)
      working-directory: ${{env.working-directory}}
      run: npm test --if-present
  
  npm_test_scraping-app:
    runs-on: ubuntu-latest
    env:
      working-directory: ./scraping
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM INSTALL
      working-directory: ${{env.working-directory}}
      run: npm ci
    - name: NPM RUN BUILD (If Present)
      working-directory: ${{env.working-directory}}
      run: npm run build --if-present
    - name: NPM TEST (If Present)
      working-directory: ${{env.working-directory}}
      run: npm test --if-present




